# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 12.5.0

package:
  name: kedro-viz
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/k/kedro-viz/kedro_viz-${{ version }}.tar.gz
  sha256: d107ef009f3f813d73e202f21579f20248f83adb3bafa57f8d19ab5ca0ac947b

build:
  number: 0
  noarch: python
  script:
    env:
      WARNINGS: ignore::kedro.KedroPythonVersionWarning
      PYTHONWARNINGS: ignore::UserWarning
    content:
      - ${{ PYTHON }} -m pip install -vv --use-pep517 --no-deps --no-build-isolation .


requirements:
  host:
    - python ${{ python_min }}.*
    - hatchling
    - hatch-requirements-txt
    - pip
  run:
    - python >=${{ python_min }}
    - aiofiles >=22.1.0
    - click-default-group
    - fastapi <0.200.0,>=0.100.0
    - fsspec >=2021.4
    - ipython <9.0,>=8.10
    - kedro >=1.0.0
    - kedro-telemetry >=0.6.0
    - networkx >=2.5
    - orjson <4.0,>=3.9
    - packaging >=23.0
    - pandas <4.0,>=2.0
    - pathspec >=0.12.1
    - plotly >=4.0
    - pydantic >=2.0.0
    - secure >=2.0.1
    - watchfiles >=1.2.0
    - werkzeug >=3.0.0
    - uvicorn <1.0,>=0.30.0
tests:
#  - python:
#      imports:
#        - kedro_viz
#      pip_check: true
#      python_version:
#        - ${{ python_min }}.*
#        - "*"
  - requirements:
      run:
        - pip
        - python ${{ python_min }}.*
    script:
      env:
        WARNINGS: ignore::kedro.KedroPythonVersionWarning
        PYTHONWARNINGS: ignore::UserWarning
      interpreter: python
      content: |
        import kedro_viz


about:
  homepage: https://kedro.org
  license: Apache-2.0
  license_file: LICENSE
  summary: Kedro-Viz helps visualise Kedro data and analytics pipelines
  description: |
    Kedro-Viz helps visualise Kedro data and analytics pipelines
  repository: https://github.com/kedro-org/kedro-viz
  documentation: https://docs.kedro.org/projects/kedro-viz

extra:
  recipe-maintainers:
    - rxm7706
    - cshaley
    - millsks
    - zaigner
    - elanqo
